### ISSUE TITLE
Option to keep executables / libraries

### ISSUE THREAD

**Issue by dnlmlr** [dnlmlr/cargo-clean-all#7]
In some cases it might be beneficial to keep the actual executables / targets of a rust project, but still delete all the other artifacts. This will free up most of the used space, but retain the possibility to use the executable in the future without needing to recompile the whole project.

To implement this feature, a few changes would have to be made:
- [ ] Find out what files should be considered as the mentioned executables / libraries somehow
- [ ] Adjust the scanning to ignore projects which *only* have these files left
- [ ] Change the recursive deletion to keep the files

**Comment by dnlmlr** [comment]
A possible different solution would be move the executable / library file to another directory (for example the main project directory) before deletion.

(The suggestion for this approach and the whole option to keep files comes from the user GoodJobNL on reddit)

**Comment by dnlmlr** [comment]
Implemented in 0.6.0

**Comment by UnknownSuperficialNight** [comment]
One little issue I have with this is i symbolic link into my target, so this moves it out so It's pretty useless for me since I would have to still go in and move it back into target or move the symbolic link-up to the new target.

**Comment by dnlmlr** [comment]
@UnknownSuperficialNight Can you elaborate on your usecase with an example, so I can better understand it? Like a rough directory structure while pointing out where you have the symbolic links and where they are pointing to? I'm sure we can figure out a simple way to avoid your issue, if I fully understand your usecase.

**Comment by UnknownSuperficialNight** [comment]
> [@UnknownSuperficialNight](https://github.com/UnknownSuperficialNight) Can you elaborate on your usecase with an example, so I can better understand it? Like a rough directory structure while pointing out where you have the symbolic links and where they are pointing to? I'm sure we can figure out a simple way to avoid your issue, if I fully understand your usecase.

Sure thing:

```
my_app_release/
│
└─ target/
    └─ release/
        ├─ my_app (This is the binary i symbolic link too)
        ├─ build/
        ├─ deps/
        └─ examples/
```

So an ideal case would simply be the rest of it cleaned up

```
my_app_release/
│
└─ target/
    └─ release/
        ├─ my_app (This is the binary i symbolic link too)
```

This way, in the future, if I go back and maybe `git pull --rebase` and recompile, I don't need to worry about symbolic links, since it will point to the newly compiled binary already apon rebuild.
